# Session 4 Data Analytics: Data manipulation and understanding

Before diving into data understanding, we will first review the key commands in the `pandas` package.   `pandas` is Python’s main data manipulation library and makes it easy to read, explore, wrangle, transform, and combine datasets. Mastering its core capabilities is essential before moving on to data understanding, exploration, and preparation.

In [ ]:
#ONLY FOR GOOGLE COLAB

# Code to access drive
from google.colab import drive
drive.mount('/content/drive')

# Set working directory to proper location
import os
os.chdir("/content/drive/MyDrive/Colab Notebooks/Data Analytics/Session 4")

# Pandas for data manipulation

## Definition

In [1]:
# import pandas package
import pandas as pd

>**Note on pandas versions:** pandas 3.0 was released recently, but this course intentionally stays on **pandas 2.x** (`pandas>=2.3,<3`). pandas 3.0 changes default behavior (copy-on-write always on, a new default string dtype) in ways that haven't been fully verified yet against the other packages we use (`feature_engine`, `sklearn_evaluation`, ...). Make sure you install the pinned environment from `requirements.txt` in the the installation guide rather than whatever pandas version `pip install pandas` gives you today.

## DataFrame Creation

In [2]:
# create DataFrame manually
df = pd.DataFrame(
    {
        "name": ["Sarah", "Tom", "Michael", "Lore"],
        "cust_id": [123, 451, 455, 388],
        "country": ["Germany", "France", "USA", "Belgium"],
    
    }
)

In [ ]:
# loading csv file
df = pd.read_csv("../data/raw/customers.csv", sep=";")

In [5]:
# check
df.head()

   Cust_ID    Name  Country      Number
0   203040  Thomas  Belgium   456203495
1   405061  Steven  Germany   459602010
2   601020   Julie   France  4050103003
3   302001  Viktor  Belgium    40501020
4  4050102   Sarah  Belgium   405010034

In [221]:
# loading xlsx file
#Make sure that you have openpyxl package installed: pip install openpyxl
df = pd.read_excel("../data/raw/customers.xlsx")

In [10]:
# check
df.head()

   Cust_ID    Name  Country      Number
0   203040  Thomas  Belgium   456203495
1   405061  Steven  Germany   459602010
2   601020   Julie   France  4050103003
3   302001  Viktor  Belgium    40501020
4  4050102   Sarah  Belgium   405010034

In [ ]:
# loading csv file
df = pd.read_csv("../data/raw/customers_no_header.csv", 
                 sep=";", 
                 header=None, 
                 names=["Cust_ID", "Name", "Country", "Number"],
                 dtype={"Cust_ID": int, "Name": str, "Country": str, "Number": float})

In [12]:
# check
df.head()

   Cust_ID    Name  Country        Number
0   203040  Thomas  Belgium  4.562035e+08
1   405061  Steven  Germany  4.596020e+08
2   601020   Julie   France  4.050103e+09
3   302001  Viktor  Belgium  4.050102e+07
4  4050102   Sarah  Belgium  4.050100e+08

## DataFrame Exploration

In [13]:
# load csv file
df = pd.read_csv("../data/raw/customer_churn.csv")

In [14]:
# print snapshot of entire dataframe
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [ ]:
# print snapshot of a specific variable
df["gender"]

0       Female
1         Male
2         Male
3         Male
4       Female
         ...
7038      Male
7039    Female
7040    Female
7041      Male
7042      Male
Name: gender, Length: 7043, dtype: object

In [15]:
# inspect first 3 rows of dataframe
df.head(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

In [16]:
# inspect last 3 rows of dataframe
df.tail(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [17]:
# inspect the shape of the dataframe
df.shape

(7043, 21)

In [18]:
# inspect column names
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
# inspect the column names
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [19]:
# get summary statistics of numeric variable
df["MonthlyCharges"].describe()

count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: MonthlyCharges, dtype: float64

In [20]:
# get summary statistics of string variable
df["gender"].describe()

count     7043
unique       2
top       Male
freq      3555
Name: gender, dtype: object

In [21]:
# get summary statistics of all numeric variables
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [22]:
# get the mean of the MonthlyCharges variable
df["MonthlyCharges"].mean()

np.float64(64.76169246059918)

In [23]:
# get the sum of the MonthlyCharges variable
df["MonthlyCharges"].sum()

np.float64(456116.6)

In [24]:
# get the number of categories of the InternetService variable
df["InternetService"].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [25]:
# check if the InternetService variable only contains unique values
df["InternetService"].is_unique

False

In [26]:
# inspect missing values per row
df["InternetService"].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: InternetService, Length: 7043, dtype: bool

In [27]:
# get number of missing values for column
df["InternetService"].isnull().sum()

np.int64(0)

In [ ]:
# get number of missing values for each column of DataFrame
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

## DataFrame Manipulation

### Type Conversion

In [28]:
# define dataframe
df_1 = pd.DataFrame(
                    {"Postal_Code": ["3410", "4515", "5511", "1390"]}
)

In [29]:
# show
df_1

  Postal_Code
0        3410
1        4515
2        5511
3        1390

In [31]:
# check data types
df_1.dtypes

Postal_Code    object
dtype: object

In [32]:
# convert string variable to numeric variable
df_1["Postal_Code"] = pd.to_numeric(df_1["Postal_Code"])

In [33]:
# show
df_1

   Postal_Code
0         3410
1         4515
2         5511
3         1390

In [34]:
# check data types
df_1.dtypes

Postal_Code    int64
dtype: object

In [35]:
# convert numeric variable back to string variable
df_1["Postal_Code"] = df_1["Postal_Code"].astype(str)

In [36]:
# define dataframe
df_1 = pd.DataFrame(
                    {"dates": ["01/04/1993", "04/11/2003", "05/03/1997", "23/06/2001"]}
)

In [37]:
df_1

        dates
0  01/04/1993
1  04/11/2003
2  05/03/1997
3  23/06/2001

In [38]:
# check data types
df_1.dtypes

dates    object
dtype: object

In [40]:
# convert string variable to datetime variable
df_1["dates"] = pd.to_datetime(df_1["dates"], format="%d/%m/%Y")

In [41]:
# check
df_1

       dates
0 1993-04-01
1 2003-11-04
2 1997-03-05
3 2001-06-23

In [42]:
df_1.dtypes

dates    datetime64[ns]
dtype: object

### Sorting

In [43]:
# define dataframe
df_1 = pd.DataFrame(
                    {"Scores": [3, 18, 15, 6],
                     "Group": [1, 2, 1, 2]}
)

In [44]:
df_1

   Scores  Group
0       3      1
1      18      2
2      15      1
3       6      2

In [45]:
# sort in ascending order
df_1.sort_values(by="Scores")

   Scores  Group
0       3      1
3       6      2
2      15      1
1      18      2

In [46]:
# sort in descending order
df_1.sort_values(by="Scores", ascending=False)

   Scores  Group
1      18      2
2      15      1
3       6      2
0       3      1

In [47]:
# sort by multiple variables
df_1.sort_values(by=["Group", "Scores"])

   Scores  Group
0       3      1
2      15      1
3       6      2
1      18      2

### Subsetting

In [48]:
# select the gender and tenure columns
df_sub = df[["gender", "tenure"]]

In [49]:
df_sub.head(3)

   gender  tenure
0  Female       1
1    Male      34
2    Male       2

In [50]:
# select row 2 and column 3
df_sub = df.iloc[1, 2]

In [51]:
df_sub

np.int64(0)

In [ ]:
# select rows 2, 5, 6 and columns 4, 5
df_sub = df.iloc[[1, 4, 5], [3, 4]]

In [53]:
df_sub

  Partner Dependents
1      No         No
4      No         No
5      No         No

In [54]:
# select row 10 until row 30 and columns 3 until 5
df_sub = df.iloc[9:30, 2:5]

In [55]:
df_sub.head()

    SeniorCitizen Partner Dependents
9               0      No        Yes
10              0     Yes        Yes
11              0      No         No
12              0     Yes         No
13              0      No         No

In [56]:
# select all the rows where gender equals Male
df_sub = df[df["gender"] == "Male"]

In [57]:
# select all the rows where tenure equals 1, 2 or 3
df_sub = df[df["tenure"].isin([1, 2, 3])]

In [58]:
# select all the rows where gender equals Male and OnlineSecurity equals yes
df_sub = df[(df["gender"] == "Male") & (df["OnlineSecurity"] == "Yes")]

In [59]:
# condition on column
df["gender"] == "Male"

0       False
1        True
2        True
3        True
4       False
        ...
7038     True
7039    False
7040    False
7041     True
7042     True
Name: gender, Length: 7043, dtype: bool

### Grouping

In [ ]:
df = pd.read_csv("../data/raw/customer_churn.csv")

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [61]:
df.groupby("gender")["MonthlyCharges"].mean()

gender
Female    65.204243
Male      64.327482
Name: MonthlyCharges, dtype: float64

In [63]:
agg_dict = {"tenure": ['mean', 'sum'], "MonthlyCharges": ['min', 'max']}

**NOTE**: In earlier versions of pandas, when using the ``agg()`` function in a groupby operation, you had to pass the **actual function**, like ``np.mean``, for aggregation. However, in more recent versions of pandas, you can simply pass the **string name of the function** (e.g., ``'mean'``, ``'sum'``, etc.) instead of the function object itself. This works because pandas internally maps these string names to the corresponding numpy functions.

In [64]:
df.groupby("gender").agg(agg_dict)

           tenure         MonthlyCharges
             mean     sum            min     max
gender
Female  32.244553  112469          18.40  118.75
Male    32.495359  115521          18.25  118.35

### Joining

In [65]:
# define dataframe
df_1 = pd.DataFrame(
                    {"Country": ["Belgium", "France", "Germany"],
                     "Name": ["Tom", "Sarah", "Niels"]}
)

In [66]:
df_1

   Country   Name
0  Belgium    Tom
1   France  Sarah
2  Germany  Niels

In [67]:
# define dataframe
df_2 = pd.DataFrame(
                    {"Country": ["Belgium", "USA"],
                     "Name": ["Lies", "Jack"]}
)

In [68]:
df_2

   Country  Name
0  Belgium  Lies
1      USA  Jack

In [69]:
# stack dataframes
pd.concat([df_1, df_2])

   Country   Name
0  Belgium    Tom
1   France  Sarah
2  Germany  Niels
0  Belgium   Lies
1      USA   Jack

In [70]:
# define dataframe
df_1 = pd.DataFrame({"Country": ["Belgium", "France", "Germany"],
                     "Name": ["Tom", "Sarah", "Niels"]})

In [71]:
df_1

   Country   Name
0  Belgium    Tom
1   France  Sarah
2  Germany  Niels

In [72]:
# define dataframe
df_2 = pd.DataFrame({"Cust_Id": [234, 4531],
                     "Name": ["Lies", "Jack"]})

In [73]:
df_2

   Cust_Id  Name
0      234  Lies
1     4531  Jack

In [74]:
# stack dataframes
pd.concat([df_1, df_2])

   Country   Name  Cust_Id
0  Belgium    Tom      NaN
1   France  Sarah      NaN
2  Germany  Niels      NaN
0      NaN   Lies    234.0
1      NaN   Jack   4531.0

In [75]:
# define dataframe
df_1 = pd.DataFrame({"Country": ["Belgium", "France", "Germany"],
                     "Name": ["Tom", "Sarah", "Niels"],})

In [76]:
df_1

   Country   Name
0  Belgium    Tom
1   France  Sarah
2  Germany  Niels

In [77]:
# define 2 dataframes
df_2 = pd.DataFrame({"Country": ["Belgium", "France", "Spain"],
                     "Prefix": ["+32", "+33", "+34"]})

In [78]:
df_2

   Country Prefix
0  Belgium    +32
1   France    +33
2    Spain    +34

In [79]:
# outer join
pd.merge(df_1, df_2, how="outer", on="Country")

   Country   Name Prefix
0  Belgium    Tom    +32
1   France  Sarah    +33
2  Germany  Niels    NaN
3    Spain    NaN    +34

In [80]:
# inner join
pd.merge(df_1, df_2, how="inner", on="Country")

   Country   Name Prefix
0  Belgium    Tom    +32
1   France  Sarah    +33

In [81]:
# left join
pd.merge(df_1, df_2, how="left", on="Country")

   Country   Name Prefix
0  Belgium    Tom    +32
1   France  Sarah    +33
2  Germany  Niels    NaN

In [82]:
# right join
pd.merge(df_1, df_2, how="right", on="Country")

   Country   Name Prefix
0  Belgium    Tom    +32
1   France  Sarah    +33
2    Spain    NaN    +34

### Dropping

In [83]:
# define dataframe
df_1 = pd.DataFrame({"Name": ["Tom", "Sarah", "Niels", "Tom", "Sarah"],
                     "Country": ["Belgium", "France", "Germany", "USA", "France"]})

In [84]:
df_1

    Name  Country
0    Tom  Belgium
1  Sarah   France
2  Niels  Germany
3    Tom      USA
4  Sarah   France

In [85]:
# drop duplicates
df_1.drop_duplicates()

    Name  Country
0    Tom  Belgium
1  Sarah   France
2  Niels  Germany
3    Tom      USA

In [86]:
# drop duplicates based on column
df_1.drop_duplicates(subset=["Name"])

    Name  Country
0    Tom  Belgium
1  Sarah   France
2  Niels  Germany

In [87]:
# drop variable
df_1.drop(columns=["Name"])

   Country
0  Belgium
1   France
2  Germany
3      USA
4   France

### Handling Missing Values

In [104]:
import numpy as np
# define dataframe
df_1 = pd.DataFrame({"Name": ["Tom", "Sarah", np.nan, "Tom", np.nan],
                     "Country": ["Belgium", "France", "Germany", "USA", np.nan]})

In [105]:
df_1

    Name  Country
0    Tom  Belgium
1  Sarah   France
2    NaN  Germany
3    Tom      USA
4    NaN      NaN

In [106]:
# drop rows with missing values
df_1.dropna()

    Name  Country
0    Tom  Belgium
1  Sarah   France
3    Tom      USA

In [107]:
# drop rows with missing values for all columns
df_1.dropna(how="all")

    Name  Country
0    Tom  Belgium
1  Sarah   France
2    NaN  Germany
3    Tom      USA

In [108]:
# keep every row with at least 1 non missing value
df_1.dropna(thresh=1)

    Name  Country
0    Tom  Belgium
1  Sarah   France
2    NaN  Germany
3    Tom      USA

In [109]:
# define dataframe
df_1 = pd.DataFrame({"Name": ["Tom", "Sarah", np.nan, "Tom", np.nan],
                     "gender": ["male", "female", "male", "male", np.nan],
                     "Spendings": [1023, 500, 120, np.nan, 203]})

In [110]:
df_1

    Name  gender  Spendings
0    Tom    male     1023.0
1  Sarah  female      500.0
2    NaN    male      120.0
3    Tom    male        NaN
4    NaN     NaN      203.0

In [111]:
# define imputation dictionary
column_imputations = {"Name": "UNKNOWN_NAME", 
                      "Spendings": 0, 
                      "gender": "male"}

In [112]:
# impute missing values
df_1.fillna(value=column_imputations)

           Name  gender  Spendings
0           Tom    male     1023.0
1         Sarah  female      500.0
2  UNKNOWN_NAME    male      120.0
3           Tom    male        0.0
4  UNKNOWN_NAME    male      203.0

### Generating new data

In [113]:
# define dataframe
df_1 = pd.DataFrame(
                    {"Spendings": [120, -5, 293, -1]}
)

In [114]:
df_1

   Spendings
0        120
1         -5
2        293
3         -1

In [115]:
# define function 
def replace_negative_values(column_obs):
    if column_obs < 0:
        return(0)
    else:
        return(column_obs)

In [116]:
# apply function on column
df_1["Spendings"].apply(replace_negative_values)

0    120
1      0
2    293
3      0
Name: Spendings, dtype: int64

In [117]:
df_1

   Spendings
0        120
1         -5
2        293
3         -1

In [118]:
# apply same function on column with lambda expression
df_1["Spendings_correct"] = df_1["Spendings"].apply(lambda x: 0 if x < 0 else x)

In [119]:
# define dataframe
df_1 = pd.DataFrame(
                    {"Spendings": [120, 34, 293, 30],
                     "Country": ["Belgium", "France", "France", "Belgium"]}
)

In [120]:
df_1

   Spendings  Country
0        120  Belgium
1         34   France
2        293   France
3         30  Belgium

In [121]:
# define function that will be applied on each column row
def replace_wrong_values(country, spendings):
    if country == "Belgium":
        return(spendings + 100)
    else:
        return(spendings - 50)

In [122]:
# apply function on column
df_1["Spendings_correct"] = df_1.apply(lambda x: replace_wrong_values(x['Country'], x['Spendings']), axis=1)

In [123]:
df_1

   Spendings  Country  Spendings_correct
0        120  Belgium                220
1         34   France                -16
2        293   France                243
3         30  Belgium                130

# Data understanding

## Case

Starting from here, we will mainly follow the theory slides and illustrate key concepts with practical examples. To do so, we will use a case study from a newspaper publishing company (NPC) to demonstrate the main steps in data understanding, and later preprocessing and preparation.

The NPC has contacted you to help address their increasing customer **churn** rates, a trend accelerated by the rise of online news, tablets, and news aggregator apps. To tackle this, the company wants to build a predictive retention (churn) model to identify customers unlikely to renew their subscriptions.

Before building such a model, it is essential to first understand the data (e.g., by using summary statistics and visualizations) and address any data quality issues. Several preprocessing steps and feature engineering tasks must also be completed before modeling.

The company has provided two initial datasets:

- **Customers**: Contains socio-demographic information about each customer.
- **Subscriptions**: Contains details about each customer's newspaper subscriptions.

**Customers Table**

| Variable    | Description                                      |
|-------------|--------------------------------------------------|
| CustomerID  | Unique customer identifier                       |
| Gender      | M = Male, F = Female, NA = Not Available         |
| DoB         | Date of Birth                                    |
| District    | Macro-geographical grouping: district 1-8        |
| ZIP         | Meso-geographical grouping                       |
| StreeID     | Micro-geographical grouping: street identifiers  |

**Subscriptions Table**

| Variable           | Description                                                                                      |
|--------------------|--------------------------------------------------------------------------------------------------|
| SubscriptionID     | Unique subscription identifier                                                                   |
| CustomerID         | Customer identifier                                                                              |
| ProductID          | Product identifier                                                                               |
| Pattern            | Delivery days pattern (e.g., 1000000 = Monday only; 1111110 = all days except Sunday)            |
| StartDate          | Subscription start date                                                                          |
| EndDate            | Subscription end date                                                                            |
| NbrNewspapers      | Total number of copies, including NbrStart                                                       |
| NbrStart           | Max number of copies before payment is received                                                  |
| RenewalDate        | Date renewal is processed                                                                        |
| PaymentType        | BT = Bank transfer, DD = Direct debit                                                            |
| PaymentStatus      | Paid or Not Paid                                                                                 |
| PaymentDate        | Date of payment                                                                                  |
| FormulaID          | Formula identifier                                                                               |
| GrossFormulaPrice  | GrossFormulaPrice = NetFormulaPrice + TotalDiscount                                              |
| NetFormulaPrice    | NetFormulaPrice = GrossFormulaPrice – TotalDiscount                                              |
| NetNewspaperPrice  | Price of a single newspaper                                                                      |
| ProductDiscount    | Discount based on the product                                                                    |
| FormulaDiscount    | Discount based on the formula                                                                    |
| TotalDiscount      | TotalDiscount = ProductDiscount + FormulaDiscount                                                |
| TotalPrice         | NbrNewspapers * NetNewspaperPrice OR NetFormulaPrice + TotalCredit                               |
| TotalCredit        | Customer’s credit from previous transactions (negative = credit, positive = debit)               |

The goal throughout the notebooks will be to understand, explore, clean, and prepare these datasets for predictive modeling.

## Reading in the data

By default, if your data files are in the same directory as your Jupyter notebook, you do not need to change anything and your data can be read in directly using standard file paths.

If your data is stored in a different location, you can change the working directory of your notebook to where the data is located using the following command:

In [124]:
# Change to the directory in which you stored your data
import os
os.chdir('/Users/matthiasbogaert/Documents/Teaching/UNamur/DataAnalytics/Lectures/Session 4 - Data understanding/Data')

Let's reset the working directory to the notebook's directory, because we will use another strategy.

In [140]:
os.chdir('/Users/matthiasbogaert/Documents/Teaching/UNamur/DataAnalytics/Lectures/Session 4 - Data understanding/')

A good practice is to create a separate `/Data` folder within your project or notebook directory to store all your datasets. This helps keep your project organized and makes managing file paths easier. For example, if your data is in a `/Data` folder in the same directory as your notebook, you can load a file using a relative path like `./Data/filename.csv`. The `.` refers to the current working directory where your notebook is located.

We can now read in the **subscriptions table**. 

The file is called `subscriptions.txt` and uses `;` as a separator.  We use `pd.read_csv()` for this, as it works for both `.csv` and `.txt` files.

In [1]:
import pandas as pd

# Read the subscriptions table (it's a .txt file with ';' as separator)
subscriptions = pd.read_csv('./Data/subscriptions.txt', sep=';')

Let's take a look at the structure of the data. We see that there are **8252 observations** and **21 variables**. Below, we display the info and summary statistics for the first couple of values of each variable.

In [2]:
# Show structure of the DataFrame
subscriptions.info()

# Show the first few rows
subscriptions.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8252 entries, 0 to 8251
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SubscriptionID     8252 non-null   int64
 1   CustomerID         8252 non-null   int64
 2   ProductID          8252 non-null   int64
 3   Pattern            8252 non-null   int64
 4   StartDate          8252 non-null   object
 5   EndDate            8252 non-null   object
 6   NbrNewspapers      8252 non-null   int64
 7   NbrStart           8231 non-null   float64
 8   RenewalDate        6232 non-null   object
 9   PaymentType        8252 non-null   object
 10  PaymentStatus      8252 non-null   object
 11  PaymentDate        7831 non-null   object
 12  FormulaID          8252 non-null   int64
 13  GrossFormulaPrice  8091 non-null   float64
 14  NetFormulaPrice    8091 non-null   float64
 15  NetNewspaperPrice  8091 non-null   float64
 16  ProductDiscount    8091 non-null   float64
 17  FormulaDiscount    8091 non-null   float64
 18  TotalDiscount      8091 non-null   float64
 19  TotalPrice         8091 non-null   float64
 20  TotalCredit        8091 non-null   float64
dtypes: float64(9), int64(6), object(6)
memory usage: 1.3+ MB

,SubscriptionID,CustomerID,ProductID,Pattern,StartDate,EndDate,NbrNewspapers,NbrStart,RenewalDate,PaymentType,...,PaymentDate,FormulaID,GrossFormulaPrice,NetFormulaPrice,NetNewspaperPrice,ProductDiscount,FormulaDiscount,TotalDiscount,TotalPrice,TotalCredit
0,1000687,286997,8,1111110,13/02/2010,14/08/2010,152,10.0,15/07/2010,BT,...,09/02/2010,8636,148.0,148.0,0.973684,0.0,0.0,0.0,148.0,0.0
1,1000823,659050,5,1111110,30/01/2010,27/02/2010,25,10.0,11/02/2010,DD,...,20/01/2010,9417,27.0,27.0,1.080000,0.0,0.0,0.0,27.0,0.0
2,1001004,608896,3,1111110,30/01/2010,09/03/2010,25,25.0,11/02/2010,DD,...,20/01/2010,5389,22.9,22.9,0.916000,0.0,0.0,0.0,22.9,0.0
3,1001130,799769,8,1111110,13/02/2010,13/03/2010,25,25.0,18/02/2010,BT,...,18/02/2010,4688,22.9,22.9,0.916000,0.0,0.0,0.0,22.9,0.0
4,1001564,451025,8,1111110,16/01/2010,13/02/2010,25,25.0,16/02/2010,BT,...,28/01/2010,9465,23.6,23.6,0.944000,0.0,0.0,0.0,23.6,0.0

In [3]:
# Show summary statistics for all columns (numeric and non-numeric)
subscriptions.describe(include='all')

,SubscriptionID,CustomerID,ProductID,Pattern,StartDate,EndDate,NbrNewspapers,NbrStart,RenewalDate,PaymentType,...,PaymentDate,FormulaID,GrossFormulaPrice,NetFormulaPrice,NetNewspaperPrice,ProductDiscount,FormulaDiscount,TotalDiscount,TotalPrice,TotalCredit
count,8.252000e+03,8.252000e+03,8252.000000,8.252000e+03,8252,8252,8252.000000,8231.000000,6232,8252,...,7831,8252.000000,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000
unique,NaN,NaN,NaN,NaN,1457,1213,NaN,NaN,745,2,...,1208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,02/01/2007,31/12/2007,NaN,NaN,01/12/2007,BT,...,19/12/2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,346,336,NaN,NaN,247,6743,...,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,5.951908e+05,4.646909e+05,6.249758,1.098604e+06,NaN,NaN,159.824285,14.995748,NaN,NaN,...,NaN,3037.575860,135.877842,133.336547,0.856182,2.459114,2.541296,5.000410,125.372010,-0.529440
std,3.359795e+05,3.220835e+05,2.319479,1.162320e+05,NaN,NaN,117.965557,7.290724,NaN,NaN,...,NaN,3337.374219,92.596151,93.253428,0.201169,24.595209,10.725060,26.597951,95.119942,5.009556
min,5.395700e+04,4.157000e+03,1.000000,1.000000e+01,NaN,NaN,2.000000,0.000000,NaN,NaN,...,NaN,33.000000,0.169733,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-235.000100
25%,3.100938e+05,1.209800e+05,5.000000,1.111110e+06,NaN,NaN,76.000000,10.000000,NaN,NaN,...,NaN,875.000000,68.000000,68.000000,0.809211,0.000000,0.000000,0.000000,29.600000,0.000000
50%,5.713405e+05,5.018730e+05,8.000000,1.111110e+06,NaN,NaN,77.000000,10.000000,NaN,NaN,...,NaN,918.000000,79.000000,79.000000,0.878289,0.000000,0.000000,0.000000,79.000000,0.000000
75%,8.621750e+05,6.885480e+05,8.000000,1.111110e+06,NaN,NaN,304.000000,25.000000,NaN,NaN,...,NaN,4926.000000,235.000000,235.000000,0.973684,0.000000,0.000000,0.000000,235.000000,0.000000
max,1.349168e+06,1.211742e+06,8.000000,1.111110e+06,NaN,NaN,354.000000,30.000000,NaN,NaN,...,NaN,17240.000000,310.914306,276.000000,1.120000,267.000000,138.000000,267.000000,635.960000,0.000000

Instead of using the simple `pd.read_csv()`command, you can also specify the `dtypes` for every columns. The decimal separator can also be specified with the `decimals`argument. We see that by default `pd.read_csv()` assigns the generic `object` type to columns. Whereas this is a very flexible column type, it is often not optimal. Here, it might be better to read in the IDs and the date variables as true`string`. For categorical variables, it is better to assign it as `category`.

In [27]:
# Set specific data types for each column
col_types = {
    "SubscriptionID": "string",
    "CustomerID": "string",
    "ProductID": "string",
    "Pattern": "string",
    "StartDate": "string",
    "EndDate": "string",
    "NbrNewspapers": "Int64", # use "Int64" to allow for missing values
    "NbrStart": "Int64", # use "Int64" to allow for missing values
    "RenewalDate": "string",
    "PaymentType": "category",
    "PaymentStatus": "category",
    "PaymentDate": "string",
    "FormulaID": "string",
    "GrossFormulaPrice": "float",
    "NetFormulaPrice": "float",
    "NetNewspaperPrice": "float",
    "ProductDiscount": "float",
    "FormulaDiscount": "float",
    "TotalDiscount": "float",
    "TotalPrice": "float",
    "TotalCredit": "float"
}

# Read the subscriptions table with specific column types and decimal separator
subscriptions = pd.read_csv( "./Data/subscriptions.txt",
    sep=";",
    header=0,
    dtype=col_types,
    decimal="."
)

#Check types
subscriptions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8252 entries, 0 to 8251
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SubscriptionID     8252 non-null   string
 1   CustomerID         8252 non-null   string
 2   ProductID          8252 non-null   string
 3   Pattern            8252 non-null   string
 4   StartDate          8252 non-null   string
 5   EndDate            8252 non-null   string
 6   NbrNewspapers      8252 non-null   Int64
 7   NbrStart           8231 non-null   Int64
 8   RenewalDate        6232 non-null   string
 9   PaymentType        8252 non-null   category
 10  PaymentStatus      8252 non-null   category
 11  PaymentDate        7831 non-null   string
 12  FormulaID          8252 non-null   string
 13  GrossFormulaPrice  8091 non-null   float64
 14  NetFormulaPrice    8091 non-null   float64
 15  NetNewspaperPrice  8091 non-null   float64
 16  ProductDiscount    8091 non-null   float64
 17  FormulaDiscount    8091 non-null   float64
 18  TotalDiscount      8091 non-null   float64
 19  TotalPrice         8091 non-null   float64
 20  TotalCredit        8091 non-null   float64
dtypes: Int64(2), category(2), float64(8), string(9)
memory usage: 1.2 MB

However, often we don't know the clasess so you read in the first lines and then set the column types

In [ ]:
# 1. Read a few rows to inspect the data
subscriptions_preview = pd.read_csv("./Data/subscriptions.txt", sep=";", nrows=5)
subscriptions_preview.head()

,SubscriptionID,CustomerID,ProductID,Pattern,StartDate,EndDate,NbrNewspapers,NbrStart,RenewalDate,PaymentType,...,PaymentDate,FormulaID,GrossFormulaPrice,NetFormulaPrice,NetNewspaperPrice,ProductDiscount,FormulaDiscount,TotalDiscount,TotalPrice,TotalCredit
0,1000687,286997,8,1111110,13/02/2010,14/08/2010,152,10,15/07/2010,BT,...,09/02/2010,8636,148.0,148.0,0.973684,0,0,0,148.0,0
1,1000823,659050,5,1111110,30/01/2010,27/02/2010,25,10,11/02/2010,DD,...,20/01/2010,9417,27.0,27.0,1.080000,0,0,0,27.0,0
2,1001004,608896,3,1111110,30/01/2010,09/03/2010,25,25,11/02/2010,DD,...,20/01/2010,5389,22.9,22.9,0.916000,0,0,0,22.9,0
3,1001130,799769,8,1111110,13/02/2010,13/03/2010,25,25,18/02/2010,BT,...,18/02/2010,4688,22.9,22.9,0.916000,0,0,0,22.9,0
4,1001564,451025,8,1111110,16/01/2010,13/02/2010,25,25,16/02/2010,BT,...,28/01/2010,9465,23.6,23.6,0.944000,0,0,0,23.6,0

In [6]:
# 2. Specify column types for full import
col_types = {
    "SubscriptionID": "string",
    "CustomerID": "string",
    "ProductID": "string",
    "Pattern": "string",
    "StartDate": "string", 
    "EndDate": "string",
    "NbrNewspapers": "Int64",  # nullable integer
    "NbrStart": "Int64",       # nullable integer
    "RenewalDate": "string",
    "PaymentType": "category",
    "PaymentStatus": "category",
    "PaymentDate": "string",
    "FormulaID": "string",
    "GrossFormulaPrice": "float",
    "NetFormulaPrice": "float",
    "NetNewspaperPrice": "float",
    "ProductDiscount": "float",
    "FormulaDiscount": "float",
    "TotalDiscount": "float",
    "TotalPrice": "float",
    "TotalCredit": "float"
}

# 3. Read the full dataset with specified column types and decimal separator
subscriptions = pd.read_csv(
    "./Data/subscriptions.txt",
    sep=";",
    dtype=col_types,
    decimal="."
)

Let's now read in the **customers** table as well. This time, we'll simply use the default `pd.read_csv()` statement without specifying all the column types up front. If needed, we can adjust the column types or address any issues after loading the data.

In [7]:
# Read the customers table using default settings
customers = pd.read_csv('./Data/customers.txt', sep=';')

# Quick look at the structure
customers.info()
customers.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1389 entries, 0 to 1388
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  1389 non-null   int64
 1   Gender      1166 non-null   object
 2   DOB         1389 non-null   object
 3   District    1389 non-null   int64
 4   ZIP         1389 non-null   int64
 5   StreeID     1389 non-null   int64
dtypes: int64(4), object(2)
memory usage: 65.2+ KB

   CustomerID Gender         DOB  District   ZIP  StreeID
0      106785      M  09/11/1934         5  3910    46362
1      910656      F  16/06/1974         5  3510    37856
2      913085      M  01/01/1900         5  3500    37513
3      658311      M  01/01/1900         1  2800    25758
4      681400      M  28/03/1952         1  2801    26360

Again a lot of `object` types are assigned. We will change them manually to the desired types.

In [8]:
# Define the desired column types
col_types = {
    "CustomerID": "string",
    "Gender": "category",
    "DOB": "string",
    "District": "category",
    "ZIP": "string",
    "StreeID": "string"
}

# Convert columns automatically
for col, dtype in col_types.items():
    customers[col] = customers[col].astype(dtype)

# Check the result
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1389 entries, 0 to 1388
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  1389 non-null   string
 1   Gender      1166 non-null   category
 2   DOB         1389 non-null   string
 3   District    1389 non-null   category
 4   ZIP         1389 non-null   string
 5   StreeID     1389 non-null   string
dtypes: category(2), string(4)
memory usage: 46.7 KB

## Testing the relationships 
Let's now take a closer look at the **relationship** between the customers and subscriptions tables.

A key question to explore is: *How many subscriptions does each customer have?*. This will help us understand the structure of the data and inform what an Entity-Relationship Diagram (ERD) might look like. To do so, we should do a left outer join on the customer and subscriptions table and count the number of subscriptions per customers.

We expect that a single customer can have multiple subscriptions, indicating a one-to-many relationship from customers to subscriptions.

In [9]:
# Merge customers with subscriptions to include all customers (even those with zero subscriptions)
merged = pd.merge(
    customers[["CustomerID"]],
    subscriptions[["CustomerID", "SubscriptionID"]],
    on="CustomerID",
    how="left"
)

# Count the number of subscriptions per customer
agg = merged.groupby("CustomerID")["SubscriptionID"].count().reset_index() # reset_index() is needed to keep both customerID and SubscriptionID as columns
agg = agg.rename(columns={"SubscriptionID": "NumSubscriptions"})

# Show summary statistics
print("Min:", agg["NumSubscriptions"].min(), "Max:", agg["NumSubscriptions"].max())

Min: 1 Max: 50

## Working with dates

Aas you might have noticed, we have kept the dated untouched until now. They are by default read-in as `object` or `string` and converted afterwards in pandas to datetime unsing `pd.to_datetime()`, which automatically handles most formats and can be customized with a `format` argument if needed.

Some of the most important date format codes in Python are:
- `%Y`: 4-digit year (e.g., 2025)  
- `%y`: 2-digit year (e.g., 25 for 2025)  
- `%m`: 2-digit month (01–12)  
- `%d`: 2-digit day of month (01–31)  
- `%H`: Hour (00–23, 24-hour clock)  
- `%I`: Hour (01–12, 12-hour clock)  
- `%p`: AM/PM  
- `%M`: Minute (00–59)  
- `%S`: Second (00–59)

Let's first change the dates in the **subscriptions** first and then the **customers** table.

In [10]:
# Select the date columns in subscriptions DataFrame
date_cols = ["StartDate", "EndDate", "PaymentDate", "RenewalDate"]

# Dates are in "day/month/year" format, specify the format
# Instead of looping, we will use apply. It is less structured but more efficient, especially for large datasets with many columns.
subscriptions[date_cols] = subscriptions[date_cols].apply(
    lambda col: pd.to_datetime(col, format="%d/%m/%Y", errors="coerce") #errors="coerce" will set invalid parsing to NaT (missing date)
    )

# The for loop would look like this:
#for col in date_cols:
#    subscriptions[col] = pd.to_datetime(subscriptions[col], format="%d/%m/%Y", errors="coerce")

# Check the result
print(subscriptions[date_cols].dtypes)
subscriptions[date_cols].head()

StartDate      datetime64[ns]
EndDate        datetime64[ns]
PaymentDate    datetime64[ns]
RenewalDate    datetime64[ns]
dtype: object

   StartDate    EndDate PaymentDate RenewalDate
0 2010-02-13 2010-08-14  2010-02-09  2010-07-15
1 2010-01-30 2010-02-27  2010-01-20  2010-02-11
2 2010-01-30 2010-03-09  2010-01-20  2010-02-11
3 2010-02-13 2010-03-13  2010-02-18  2010-02-18
4 2010-01-16 2010-02-13  2010-01-28  2010-02-16

In [11]:
# For the customers table
customers["DOB"] = pd.to_datetime(customers["DOB"], format="%d/%m/%Y", errors="coerce")

# Check the result
print(customers["DOB"].dtypes)
customers["DOB"].head()

datetime64[ns]

0   1934-11-09
1   1974-06-16
2   1900-01-01
3   1900-01-01
4   1952-03-28
Name: DOB, dtype: datetime64[ns]

## Statistical Data exploration

To improve our understanding of the data, we will examine key summary statistics for the main variables. This will help us gain insights into the overall structure and distribution of the datasets.

In [12]:
# Summarize a categorical variable
subscriptions["PaymentStatus"].value_counts(dropna=False)

PaymentStatus
Paid        7831
Not Paid     421
Name: count, dtype: int64

In [13]:
# Categorical variable summary (alternative: describe)
subscriptions["PaymentStatus"].describe()

count     8252
unique       2
top       Paid
freq      7831
Name: PaymentStatus, dtype: object

In [14]:
# Summarize a numeric variable
subscriptions["TotalPrice"].describe()

count    8091.000000
mean      125.372010
std        95.119942
min         0.000000
25%        29.600000
50%        79.000000
75%       235.000000
max       635.960000
Name: TotalPrice, dtype: float64

In [15]:
# Mean
subscriptions["TotalPrice"].mean(skipna=True)

np.float64(125.3720096403411)

In [16]:
# Variance
subscriptions["TotalPrice"].var(skipna=True)

np.float64(9047.803316850834)

In [17]:
# Standard deviation
subscriptions["TotalPrice"].std(skipna=True)

np.float64(95.11994174120815)

In [18]:
# Which values are not missing in TotalPrice?
subscriptions["TotalPrice"].notna().head()

0    True
1    True
2    True
3    True
4    True
Name: TotalPrice, dtype: bool

In [19]:
# Correlation between two variables
subscriptions[["TotalPrice", "NbrNewspapers"]].corr().loc["TotalPrice", "NbrNewspapers"]

np.float64(0.898895317946639)

In [20]:
# Range of a variable
(subscriptions["TotalPrice"].min(skipna=True), subscriptions["TotalPrice"].max(skipna=True))

(np.float64(0.0), np.float64(635.96))

In [21]:
# Minimum
subscriptions["TotalPrice"].min(skipna=True)

np.float64(0.0)

In [22]:
# Maximum
subscriptions["TotalPrice"].max(skipna=True)

np.float64(635.96)

In [23]:
# Is this a numeric vector?
(pd.api.types.is_numeric_dtype(subscriptions["TotalPrice"]), pd.api.types.is_numeric_dtype(subscriptions["CustomerID"]))

(True, False)

In [24]:
# Summary statistics for all columns
subscriptions.describe(include="all")

,SubscriptionID,CustomerID,ProductID,Pattern,StartDate,EndDate,NbrNewspapers,NbrStart,RenewalDate,PaymentType,...,PaymentDate,FormulaID,GrossFormulaPrice,NetFormulaPrice,NetNewspaperPrice,ProductDiscount,FormulaDiscount,TotalDiscount,TotalPrice,TotalCredit
count,8252,8252,8252,8252,8252,8252,8252.0,8231.0,6232,8252,...,7831,8252,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000
unique,8252,1389,8,11,NaN,NaN,<NA>,<NA>,NaN,2,...,NaN,621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,1000687,663946,8,1111110,NaN,NaN,<NA>,<NA>,NaN,BT,...,NaN,924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,50,4383,8147,NaN,NaN,<NA>,<NA>,NaN,6743,...,NaN,425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,2008-09-09 01:25:30.392632320,2009-03-11 22:57:52.612699904,159.824285,14.995748,2009-06-08 11:29:16.097561088,NaN,...,2008-08-17 02:57:37.949176320,NaN,135.877842,133.336547,0.856182,2.459114,2.541296,5.000410,125.372010,-0.529440
min,NaN,NaN,NaN,NaN,2006-01-02 00:00:00,2007-01-02 00:00:00,2.0,0.0,2007-09-26 00:00:00,NaN,...,2005-12-14 00:00:00,NaN,0.169733,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-235.000100
25%,NaN,NaN,NaN,NaN,2007-09-30 00:00:00,2008-03-08 00:00:00,76.0,10.0,2008-09-01 00:00:00,NaN,...,2007-08-30 12:00:00,NaN,68.000000,68.000000,0.809211,0.000000,0.000000,0.000000,29.600000,0.000000
50%,NaN,NaN,NaN,NaN,2008-10-01 00:00:00,2009-03-17 12:00:00,77.0,10.0,2009-06-01 00:00:00,NaN,...,2008-09-15 00:00:00,NaN,79.000000,79.000000,0.878289,0.000000,0.000000,0.000000,79.000000,0.000000
75%,NaN,NaN,NaN,NaN,2009-09-11 00:00:00,2010-02-18 00:00:00,304.0,25.0,2010-03-22 00:00:00,NaN,...,2009-08-14 00:00:00,NaN,235.000000,235.000000,0.973684,0.000000,0.000000,0.000000,235.000000,0.000000
max,NaN,NaN,NaN,NaN,2011-02-24 00:00:00,2011-03-02 00:00:00,354.0,30.0,2011-02-02 00:00:00,NaN,...,2011-01-27 00:00:00,NaN,310.914306,276.000000,1.120000,267.000000,138.000000,267.000000,635.960000,0.000000
std,NaN,NaN,NaN,NaN,NaN,NaN,117.965557,7.290724,NaN,NaN,...,NaN,NaN,92.596151,93.253428,0.201169,24.595209,10.725060,26.597951,95.119942,5.009556

In [25]:
# Only for the numeric columns
subscriptions.select_dtypes(include="number").describe()

,NbrNewspapers,NbrStart,GrossFormulaPrice,NetFormulaPrice,NetNewspaperPrice,ProductDiscount,FormulaDiscount,TotalDiscount,TotalPrice,TotalCredit
count,8252.0,8231.0,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000,8091.000000
mean,159.824285,14.995748,135.877842,133.336547,0.856182,2.459114,2.541296,5.000410,125.372010,-0.529440
std,117.965557,7.290724,92.596151,93.253428,0.201169,24.595209,10.725060,26.597951,95.119942,5.009556
min,2.0,0.0,0.169733,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-235.000100
25%,76.0,10.0,68.000000,68.000000,0.809211,0.000000,0.000000,0.000000,29.600000,0.000000
50%,77.0,10.0,79.000000,79.000000,0.878289,0.000000,0.000000,0.000000,79.000000,0.000000
75%,304.0,25.0,235.000000,235.000000,0.973684,0.000000,0.000000,0.000000,235.000000,0.000000
max,354.0,30.0,310.914306,276.000000,1.120000,267.000000,138.000000,267.000000,635.960000,0.000000

Visualizing the data is an effective way to deepen our understanding of its structure and quality. Basic plots can help reveal data quality issues, such as missing values or unusually large ranges that may indicate outliers. You can already spot from the descriptives that there are variables with missing values and some large ranges. 

We will explore these aspects further through data visualization and preprocessing in the next lecture.

## Save the data for future referencing

To enhance working with the datasets in future sessions, we will store the datasets as `parquet` files. Parquet is a highly efficient, compressed, and columnar storage format that ensures faster read/write operations and reduced file size.

In [26]:
# Save the subscriptions dataset as a Parquet file
subscriptions.to_parquet('./Data/subscriptions.parquet', index=False)

# Save the customers dataset as a Parquet file
customers.to_parquet('./Data/customers.parquet', index=False)